# Generated by Django 3.2.6 on 2021-08-12 15:19

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=cloudinary.models.CloudinaryField(blank='true', max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
    ]
